////////////////////////////////////////////////////////////////////////////////
//
//  File          : verify.c
//  Description   : This contains the main function for a verification tool
//                  used to check the output of the CMPSC 311 HW3 SMSA program
//                  by comparing outputs with md5sums. The verification program
//                  uses a known correct file with correct output containing
//                  checksums generated from a correct implementation of the
//                  homework to compare against a student's output file or
//                  piped program output.
//
//   Author : Eric D. Kilmer <eyk5120@psu.edu>
//   Last Modified : Dec. 2 19:02 EST 2013
//

// Include files
#include <stdio.h>
#include <string.h>

// Project includes


// Defines
// Token which indicates a line to compare
#define OUTPUT_TOK "[OUTPUT]"
#define CYCLE_TOK "Cycle"
#define MAX_LINE_LEN 256

// Output indicators for which line belongs to which file
#define MASTER_IND  "MASTER  >>>>>"
#define STUDENT_IND "STUDENT >>>>>"

#define USAGE \
  "\nUSAGE: verify <master-file> <client-log> <server-log>\n" \
  "Verifies the output of the student's client and server logs against a" \
  "known master output file. The master file should consist of a" \
  "concatenation of a client log first and then a server log." \
  "\n" \
  "All student files should be obtained WITHOUT the use of the -v option." \
  "\n" \
  "where:\n" \
  "   <master-file> - The correct md5sum values generated by a known" \
  "         correct implementation of smsasim. Contains a concatenation" \
  "         of the client and server output.\n" \
  "   <client-file> - The student's output from their client program.\n" \
  "   <server-log>  - The student's output from their server program.\n" \
  "\n"

// Fancy color escapes code output
#define ANSI_COLOR_RED     "\x1b[31m"
#define ANSI_COLOR_GREEN   "\x1b[32m"
#define ANSI_COLOR_RESET   "\x1b[0m"

//
// Global Data
char *master_out = NULL, *student_out = NULL, *master_cycle_out = NULL;
char *stud_cycle_out = NULL;

//
// Functional Prototypes
int verify_line( char *master, char *student );
int verify_files( FILE *master, FILE *clnt, FILE *srvr );

////////////////////////////////////////////////////////////////////////////////
//
// Function     : main
// Description  : The main function for the verify program.
//
// Inputs       : argc - the number of command line parameters
//                argv - the parameters
// Outputs      : 0 if successful verification, -1 if mismatch

int main( int argc, char **argv ) {
  FILE *master, *clnt, *srvr;
  master = NULL;
  clnt = NULL;
  srvr = NULL;

  unsigned int mismatches;
  
  // Two arguments means that we are comparing two files where the first input
  // is the master and the second one is the student's.
  if ( argc == 4 ) {
    master = fopen( argv[1], "r" );
    clnt = fopen( argv[2], "r" );
    srvr = fopen( argv[3], "r" );

    // Check if we failed to open the files.
    if ( !master ) {
      printf( "Error trying to open master file: [%s]\n", argv[1] );
      return ( -1 );
    }
    if ( !clnt ) {
      printf( "Error trying to open cliet file: [%s]\n", argv[2] );
    }
    if ( !srvr ) {
      printf( "Error trying to open srvr file: [%s]\n", argv[2] );
    }
  }
  // Incorrect 
  else {
    fprintf( stderr, "Incorrect usage:\n" );
    fprintf( stderr, USAGE );
    return ( -1 );
  }

  printf( "Beginning diff check:\n\n" );
  // Verify that student files match master file.
  mismatches = verify_files( master, clnt, srvr );

  // Clean up after ourselves.
  fclose( master );
  master = NULL;
  fclose( clnt );
  clnt = NULL;
  fclose( srvr );
  srvr = NULL;

  // Return
  if ( mismatches ) {
    return ( -1 );
  }

  return ( 0 );
}


////////////////////////////////////////////////////////////////////////////////
//
// Function     : verify_line
// Description  : Function verifies a single line from the master file and
//                student file.
//
// Inputs       : master - The master's line.
//                student - The student's line.
// Outputs      : 0 if matching, 1 if mismatch 

int verify_line( char *master, char *student ) {
  int cmp;

  // If an output token does not exist in the line, then return a mismatch
  if ( !master || !student ) {
    return ( 0 );
  }

  // Compare the strings to check for a match.
  cmp = strcmp( master, student );

  // Print out the diff of the master and student if they are different
  if ( cmp ) {
    printf( ANSI_COLOR_GREEN "%s %s" ANSI_COLOR_RESET, 
        MASTER_IND, master );
    printf( ANSI_COLOR_RED "%s %s\n" ANSI_COLOR_RESET, 
        STUDENT_IND, student );
    return ( 1 );
  }

  return ( 0 );
}

////////////////////////////////////////////////////////////////////////////////
//
// Function     : verify_files
// Description  : Verifies the student's file by comparing md5sums against the
//                master's file.
//
// Inputs       : master - the master file.
//                student - the student's file.
// Outputs      : The number of mismatches (0 for success)

int verify_files( FILE *master, FILE *clnt, FILE *srvr ) {
  unsigned int mismatched, total;
  char line_master[MAX_LINE_LEN], line_clnt[MAX_LINE_LEN], line_srvr[MAX_LINE_LEN];

  // Check that files are valid
  if ( !( master && clnt && srvr ) ) {
    printf( "File invalid." );
    return ( -1 );
  }

  mismatched = 0;
  total = 0;

  // Read through all lines of master and student in compare them while keeping
  // track of both the number of mismatches and total number of comparisons.
  
  // Reading from files.
  // Make sure next line read isn't NULL
  while ( fgets(line_master, MAX_LINE_LEN, master) && 
          fgets(line_clnt, MAX_LINE_LEN, clnt) ) {
    // Check if we are at the cycle line. This is not compared to the professor's
    // output. Keep the output till the end and then print
    if ( !stud_cycle_out ) {
      stud_cycle_out = strstr( line_clnt, CYCLE_TOK );
      if ( stud_cycle_out ) {
        fgets(line_clnt, MAX_LINE_LEN, clnt);
      }
      if ( feof(clnt) ) { break; }
    }

    // Look for output token
    while ( !(master_out = strstr( line_master, OUTPUT_TOK )) ) {
      fgets(line_master, MAX_LINE_LEN, master);
    }
    while ( !(student_out = strstr( line_clnt, OUTPUT_TOK )) ) {
      fgets(line_clnt, MAX_LINE_LEN, clnt);
    }

    mismatched += verify_line( master_out, student_out );
    total++;
  }

  while ( !feof( master ) && !feof( srvr ) ) {
    // Get line from server file and not master file because we read master
    // file in previous loop
    fgets(line_srvr, MAX_LINE_LEN, srvr);

    // See if we are getting the master's cycle count
    if ( !master_cycle_out ) {
      master_cycle_out = strstr( line_master, CYCLE_TOK );
    }

    // Find next output line on master
    while ( !feof( master) && 
        !(master_out = strstr( line_master, OUTPUT_TOK )) ) {
      fgets(line_master, MAX_LINE_LEN, master);
    }
    // Find next output line on server
    while ( !feof( srvr ) && 
        !(student_out = strstr( line_srvr, OUTPUT_TOK )) ) {
      fgets(line_srvr, MAX_LINE_LEN, srvr);
    }
    // Compare master and server lines
    mismatched += verify_line( master_out, student_out );
    total++;
    
    // Get next line from master
    fgets(line_master, MAX_LINE_LEN, master);

  }

  // If we found both, print out as reference
  //if ( master_cycle_out && stud_cycle_out ) {
    printf( "%s %s", MASTER_IND, master_cycle_out );
    printf( "%s %s\n", STUDENT_IND, stud_cycle_out );
  //}

  // Print out the mismatches and a status of whether the verification was
  // successful or not.
  printf("Number correct / Total compared: %d/%d\n", total-mismatched, total);
  if ( mismatched ) {
    printf( ANSI_COLOR_RED      "Failed.\n"     ANSI_COLOR_RESET);
  }
  else {
    printf( ANSI_COLOR_GREEN    "Success.\n"    ANSI_COLOR_RESET);
  }

  return ( mismatched );
}
